package airy.testRegistration;

import airy.TestBase;
import airy.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;

public class MainPageTest extends TestBase {

    @Tag("MainPage")
    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.sdvor.com/'", () ->
                open("https://www.sdvor.com/"));

        step("Page title should have text 'Строительный Двор – интернет-магазин стройматериалов'", () -> {
            String expectedTitle = "Строительный Двор – интернет-магазин стройматериалов";
            String actualTitle = title();

            Assertions.assertThat(actualTitle).contains(expectedTitle);
        });
    }
    @Tag("MainPage")
    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.sdvor.com/'", () ->
                open("https://www.sdvor.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}
